name: gaussian_splatting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - plyfile
  - python=3.12
  - pip
  - pytorch
  - torchaudio
  - torchvision
  - pytorch-cuda=12.4
  - tqdm
  - scipy
  - pip:
    - submodules/diff-gaussian-rasterization
